### ISSUE TITLE
Schiffeversenken als Stack Projekt builden und Code in Module zerlegen

### ISSUE THREAD

**Issue by fft5woosh** [ob-fun-ws18/studienarbeit-roteroktober#1]
Der Code ist soweit vollständig.
Deswegen habe ich gestern ein neues Stackprojekt erstellt und den ganzen Code in die Main.hs kopiert.
Im Branch finalercode findet man das Projekt.
Leider funktioniert der Build nicht, weil ich vermute das irgendwelche Dependencies fehlen.
Wissen Sie vielleicht was zu tun ist @obcode  ?

**Comment by obcode** [comment]
was heisst der Build funktioniert nicht? Es sollte alles toplevel liegen. Insbesondere die travis.yaml **muss** toplevel sein.

**Comment by Sup3rdom** [comment]
Vielen Dank @obcode, das Problem hat sich erledigt.
@fft5woosh Der build funktioniert, check den branch origin/master aus, habe alle fehlenden dependencies ergänzt (Die Warnungen wegen der veralteten Methoden bleiben bestehen).

**Comment by Sup3rdom** [comment]
Außerdem ist der Code jetzt toplevel im Master.
